sort:
  by: required

content: |-
  {{ .Header }}
  # Imperva WAF Gateway Management Server on Google Cloud
  This Terraform module provisions an Imperva WAF Gateway Management Server (also known as 'MX') on GCP.
  The MX is a critical component in the Imperva WAF Gateway architecture, serving as the centralized management interface for configuring Imperva WAF Gateways.

  {{ .Requirements }}

  For the GCP prerequisites, please see the [documentation](https://docs.imperva.com/bundle/v15.3-waf-on-google-cloud-platform-installation-guide/page/84150.htm).

  ## Usage
  ### Basic example
  ```hcl
  provider "google" {
    project = "my-project"
    region = "europe-west3"
  }

  variable "mx_password" {
    type = string
    description = "The password for the WAF Management Server"
    sensitive = true
  }

  module "imperva_mx" {
    source = "imperva/wafgateway/mx/google"
    waf_version = "15.3.0.20"
    mx_password = var.mx_password
    vpc_network = "my-vpc-network"
    subnet_name = "my-subnet"
    timezone = "UTC"
    instance_type = "n2-standard-4"
    zone = "europe-west3-a"
    ssh_access_source_ranges = ["10.0.1.0/24", "10.0.2.0/24"]
    ui_access_source_ranges = ["10.0.0.0/8"]
  }
  ```
  ### Supported WAF Gateway versions
  This version of the module supports the following WAF Gateway versions:
  * 14.7.0.110
  * 14.7.0.120
  * 14.7.0.130
  * 15.2.0.10
  * 15.3.0.10
  * 15.3.0.20

  The `waf_version` input variable must be set to one of these versions. If you need to use a different version, please open an issue or pull request.

  ### Cross-module reference
  If you are using the Gateway module in conjunction with the MX module, you can reference the MX outputs directly in the Gateway module configuration:
  ```hcl
  module "imperva_gw" {
    source = "imperva/wafgateway/gw/google"
    waf_version = "15.3.0.20"
    management_server_config = {
      ip = module.imperva_mx.management_server_ip
      password = var.mx_password
      vpc_network = "my-vpc-network"
      network_tag = module.imperva_mx.network_tag
    }
    ...
  }
  ```
  This allows you to register your WAF Gateway instances to your MX without defining explicit dependencies or hard-coding the MX IP address or network tag.
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Footer }}
